language: node_js

node_js:  
  - "12"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/user

before_script:
  - psql -c 'create database user' -U postgres
  - psql -U postgres -d user -a -f table.sql

services:
  - postgresql